### ISSUE TITLE
Scripts to analyze .dec files

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/mc_tools#1]
@yipengsun we need a couple of fairly straightforward scripts to more easily study the `.dec` files that probably won't take you long. They would allow us at a glance to see which particles are decayed, with which FFs and BFs with the file, and you will gain some familiarity with the configuration of the MC we will be producing

- [x] A script that takes as input a `.dec` file and outputs only the decays in the file, with their branching fractions normalized to 1 with 4 decimals. For instance, the beginning of the output for [11873010](https://gitlab.cern.ch/lhcb-datapkg/Gen/DecFiles/-/blob/v30r46/dkfiles/Bd_Dststmunu,D0=cocktail,TightCuts.dec) would be
```
Decay B0sig 
  0.2970  MyD_0*-    mu+  nu_mu         PHOTOS  ISGW2;
  0.3069  MyD'_1-    mu+  nu_mu         PHOTOS  ISGW2;
  0.2772  MyD_1-     mu+  nu_mu         PHOTOS  ISGW2;
  0.1188  MyD_2*-    mu+  nu_mu         PHOTOS  ISGW2;
Decay Mytau-
  1.0000   mu-   nu_tau    anti-nu_mu        PHOTOS  TAULNUNU;
Decay MyD0
  1.0000   K-  pi+                              PHOTOS PHSP;
Decay MyD*0
  0.6190   MyD0  pi0                            PHOTOS VSS;
  0.3810   MyD0  gamma                          PHOTOS VSP_PWAVE;
...
```
- [x] A script that downloads the `.dec` files taking the MC type, and matching it to the gitlab link with this [site](http://lhcbdoc.web.cern.ch/lhcbdoc/decfiles/releases/latest/table_evttype.php). To download the file it would simply be
```
get_dec_file.py 11873010
```
Could you do the first by tomorrow's meeting?

**Comment by yipengsun** [comment]
@manuelfs Done for the first task. You can refer to the project's README on how to use it.

**Comment by yipengsun** [comment]
Also, for each decay mother, the decay modes are printed in the descending order of the BF.

**Comment by yipengsun** [comment]
For the second objective: I think that site is partially broken. For example, the first event type contains many numerical IDs (NIDs), but the only link on that site is to NID `10000000`.

**Comment by yipengsun** [comment]
BTW, that website already does what you need for objective 2. Do you just want a cli-tool to do that?

**Comment by manuelfs** [comment]
Remember to be more verbose! Is this the script you are talking about?
https://github.com/umd-lhcb/mc_tools/blob/master/bin/dec_print.py

If so, it does not seem to do the normalization to 1 and it removes `PHOTOS`?
```
|09:11:31|~/code/mc_tools$ ./bin/dec_print.py dec_files/lhcb-semileptonic/11873010.dec 
/Users/manuelf/.pyenv/versions/3.8.3/lib/python3.8/site-packages/decaylanguage/dec/dec.py:447: UserWarning: 
Corresponding 'Decay' statement for 'CDecay' statement(s) of following particle(s) not found:
anti-B0sig.
Skipping creation of these charge-conjugate decay trees.
  warnings.warn(msg)
Decay B0sig
  0.0031 : MyD'_1-  mu+  nu_mu                                          ISGW2 
  0.0030 : MyD_0*-  mu+  nu_mu                                          ISGW2 
  0.0028 : MyD_1-  mu+  nu_mu                                           ISGW2 
  0.0012 : MyD_2*-  mu+  nu_mu                                          ISGW2 
Decay Mytau-
  0.1736 : mu-  nu_tau  anti-nu_mu                                   TAULNUNU 
```
The normalization is the main feature needed.

Yes, script 2 is just a quick way to find the `.dec` files we are interested in from the command line. Thanks.

**Comment by yipengsun** [comment]
I have addressed both issues for the first script.

**Comment by manuelfs** [comment]
It looks great, thank you. It even reorders the decays with decreasing BFs!

**Comment by yipengsun** [comment]
@manuelfs I finished the `.dec` downloader. Please refer to the README for usage.

**Comment by manuelfs** [comment]
Thank you Yipeng! It works great. 

I modified it so that it replaces `,` and `=` with `-` and `--`, and prints the files generated. This needs to be a general rule for our tools: if a scripts produces a plot, table, or file in general, it needs to print its name. To make more useful, I write the printout as ` open <generated_file>`, so that I can copy paste it and open it in a Mac (the initial space is to more easily copy it).
