### ISSUE TITLE
Bug in decay model parsing when name includes numbers (probably in `decaylanguage`)

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/mc_tools#2]
I am posting this here to confirm with @yipengsun that this looks like a bug in `decaylanguage` before posting an issue over there.

I noticed that `bin/dec_print.py` returned the wrong decay models when the name of the model included numbers (ig, `HQET2`). For instance, it converted
```
0.049300	MyD*-	mu+	nu_mu		HQET2 1.207 0.908 1.406 0.853;
```
to
```
0.6463   MyD*- mu+ nu_mu    HQET 2.0 1.207 0.908 1.406 0.853;
```

I made a minimal example to check that the error seems to be in the parser
```python
from decaylanguage import DecFileParser

s = """Decay B0sig
0.0030  MyD_0*- mu+ nu_mu       PHOTOS  ISGW2;
0.0493  MyD*-   mu+ nu_mu       HQET2 1.207 0.908 1.406 0.853;
0.0493  MyD*-   mu+ nu_mu       HQET 1.207 0.908 1.406 0.853;
Enddecay
"""

dfp = DecFileParser.from_string(s)
dfp.parse()
dms = dfp._find_decay_modes('B0sig')
for dm in dms:
    dm_details = dfp._decay_mode_details(dm, True)
    for detail in dm_details:
        print(detail)  
```
outputs
```
(base) |09:12:17|~/code/mc_tools$ ./test.py 
0.003
['MyD_0*-', 'mu+', 'nu_mu']
ISGW
[2.0]
0.0493
['MyD*-', 'mu+', 'nu_mu']
HQET
[2.0, 1.207, 0.908, 1.406, 0.853]
0.0493
['MyD*-', 'mu+', 'nu_mu']
HQET
[1.207, 0.908, 1.406, 0.853]
```

Indicating that both for `HQET2` and `ISGW2`, the number is taken as a model parameter. I checked this was the behavior with `decaylanguage` 0.10.3 and 0.11.2 (the [latest tag](https://github.com/scikit-hep/decaylanguage/tags) I could find).

Should we open an issue at https://github.com/scikit-hep/decaylanguage/issues ?

**Comment by yipengsun** [comment]
Yeah, this definitely feels like a parsing bug. I'll take a look at the lark parsing rule to see if I can propose an easy fix. If not, let's open a bug report upstream indeed.

**Comment by yipengsun** [comment]
I can confirm the current master branch is still problematic with the following modified reproducer:
```python
from decaylanguage import DecFileParser
from decaylanguage.dec.dec import get_model_name

s = """Decay B0sig
0.0030  MyD_0*- mu+ nu_mu       PHOTOS  ISGW2;
0.0493  MyD*-   mu+ nu_mu       HQET2 1.207 0.908 1.406 0.853;
0.0493  MyD*-   mu+ nu_mu       HQET 1.207 0.908 1.406 0.853;
Enddecay
"""

dfp = DecFileParser.from_string(s)
dfp.parse()
dms = dfp._find_decay_modes('B0sig')
for dm in dms:
    dm_details = dfp._decay_mode_details(dm, True)

    print('Model name: ', get_model_name(dm))

    for detail in dm_details:
        print(detail)
```

**Comment by yipengsun** [comment]
I tried to add various small tweaks to the dec file lark parser and none worked. I give up. We should file a bug report upstream

**Comment by yipengsun** [comment]
This bug has been fixed by upstream. Closed.
